# Generated by Django 5.2.10 on 2026-01-17 02:12

from django.db import migrations


def copy_owner_to_owner_user(apps, schema_editor):
    Machine = apps.get_model('core', 'Machine')
    for machine in Machine.objects.all():
        machine.owner_user_id = machine.owner_id
        machine.save(update_fields=['owner_user'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_owner_user_nullable'),
    ]

    operations = [
        migrations.RunPython(copy_owner_to_owner_user),
    ]
