# Generated by Django 5.2.10 on 2026-01-17 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='owner_user',
            field=models.ForeignKey(
                to='core.user',
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
    ]
