# Generated by Django 5.2.10 on 2026-01-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_make_owner_user_not_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='owner',
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='working_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('STANDBY', 'Standby'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='status',
            field=models.CharField(choices=[('STANDBY', 'Standby'), ('ONGOING', 'Ongoing'), ('HALT', 'Halt'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
