# Generated by Django 5.2.10 on 2026-01-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_machine_owner_productionmachine_working_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmachine',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='working_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
