# Generated by Django 5.1.4 on 2026-01-10 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('model', models.CharField(max_length=255)),
                ('serialnumber', models.CharField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('STANDBY', 'STANDBY'), ('ONGOING', 'ONGOING'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='STANDBY', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductionMachine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('STANDBY', 'STANDBY'), ('ONGOING', 'ONGOING'), ('HALT', 'HALT'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='STANDBY', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.PROTECT, related_name='production_machines', to='factory.machine')),
                ('production', models.ForeignKey(db_column='production_id', on_delete=django.db.models.deletion.CASCADE, related_name='production_machines', to='factory.production')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='production',
            name='machines',
            field=models.ManyToManyField(related_name='productions', through='factory.ProductionMachine', to='factory.machine'),
        ),
        migrations.AddConstraint(
            model_name='productionmachine',
            constraint=models.UniqueConstraint(fields=('production', 'machine'), name='uniq_production_machine'),
        ),
    ]
