# Generated by Django 5.1.4 on 2026-01-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmachine',
            name='working_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
